name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"   # 9:00 AM IST

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '18'

      - name: Install LeetCode CLI
        run: npm install -g leetcode-cli

      - name: Export solutions
        run: leetcode export -o ./solutions
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "[LeetCode Sync] Auto-update solutions"

          git push
